name: Changelog CI

# Controls when the action will run. Triggers the workflow on a pull request
on:
  pull_request:
    branches: [ master ]
    types: [ opened, reopened ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v0.8.0
        with:
          changelog_filename: CHANGELOG.md
          config_file: changelog-ci-config.yml
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}