name: Secrets Check

env:
  GITHUB_SHA: ${{ github.sha }}
  
on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo $GITHUB_SHA'
      - uses: actions/checkout@v1
      - name: gitleaks-action
        uses: eshork/gitleaks-action@v1.0.0
        with:
          args: --commit=$GITHUB_SHA
