name: Secrets Check - Commit
  
on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Trufflehog Actions Scan test
        uses: nasa-gibs/trufflehog-actions-scan@master
        with:
          githubToken: ${{ secrets.GITHUB_CLONE_TOKEN }}
          scanArguments: "--regex --entropy=False --max_depth=13"
