name: Secrets Check - Commit
  
on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: trufflehog-action
        uses: dxa4481/truffleHog@master
        with:
          run: |
            set -e
            trufflehog --regex --since_commit $GITHUB_SHA $GITHUB_WORKSPACE \
