name: Secrets Check - Commit
  
on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Secret Scan
        uses: max/secret-scan@1.0.0
        with:
          run: |
            trufflehog https://github.com/edplato/linkCrawl.git \
            
            
